K_epochs: 80
action_std: 0.6
action_std_decay_freq: 10
action_std_decay_rate: 0.05
min_action_std: 0.1
device: cuda
env_name: BipedalWalker-v3
eps_clip: 0.2
exp_name: lstm
gamma: 0.99
has_continuous_action_space: true
lr_actor: 0.0003
lr_critic: 0.0003
max_updates: 110
num_mini_batch: 4
ppo:
  entropy_coeff: 0
  vf_loss_coeff: 0.5
random_seed: 0
recurrence:
  hidden_state_size: 64
  layer_type: gru
  reset_hidden_state: true
  sequence_length: 64
  use_lstm: true
save_model_freq: 10
worker:
  num_workers: 6
  worker_steps: 1600
