K_epochs: 4
device: cuda
env_name: CarRacing-v1
eps_clip: 0.2
exp_name: lstm_continue
gamma: 0.99
has_continuous_action_space: true
lr_actor: 0.0002
lr_critic: 0.0002
max_updates: 500
num_mini_batch: 8
hidden_layer_size: 512
ppo:
  entropy_coeff: 0.001
  vf_loss_coeff: 0.5
random_seed: 0
recurrence:
  hidden_state_size: 256
  layer_type: gru
  reset_hidden_state: true
  sequence_length: 8
  use_lstm: true
save_model_freq: 10
worker:
  num_workers: 6
  worker_steps: 256
