ppo:
  entropy_coeff: 0.01
  eps_clip: 0.2
  gamma: 0.99
  lamda: 0.95
  lr: 0.0002
  lr_std: 0.0002
  vf_loss_coeff: 0.5
recurrence:
  hidden_state_size: 256
  layer_type: gru
  reset_hidden_state: true
  sequence_length: 8
  use_lstm: true
train:
  K_epochs: 4
  device: cuda
  env_name: CarRacing-v1
  exp_name: lstm_continue
  has_continuous_action_space: true
  hidden_layer_size: 512
  max_updates: 500
  num_mini_batch: 8
  random_seed: 0
  save_model_freq: 10
worker:
  num_workers: 6
  worker_steps: 512
