K_epochs: 80
device: cuda
env_name: CarRace
eps_clip: 0.2
exp_name: test
gamma: 0.99
has_continuous_action_space: true
lr_actor: 0.0003
lr_critic: 0.001
max_updates: 1000
num_mini_batch: 4
ppo:
  entropy_coeff: 0.001
  vf_loss_coeff: 0.5
random_seed: 0
recurrence:
  hidden_state_size: 32
  layer_type: gru
  reset_hidden_state: true
  sequence_length: 64
  use_lstm: true
save_model_freq: 10
worker:
  num_workers: 12
  worker_steps: 500
