ppo:
  entropy_coeff_schedule:
    init: 0.1
    final: 0.001
    pow: 1.0
    max_decay_steps: 400
  clip_range_schedule:
    init: 0.3
    final: 0.2
    pow: 1.0
    max_decay_steps: 450
  lr_schedule:
    init: 3.0e-4
    final: 3.0e-5
    pow: 1.0
    max_decay_steps: 450
  gamma: 0.99
  lamda: 0.95
  vf_loss_coeff: 0.01
recurrence:
  hidden_state_size: 256
  layer_type: gru
  reset_hidden_state: true
  sequence_length: 8
  use_lstm: true
train:
  K_epochs: 4
  device: cuda
  env_name: CarSearchCkpt
  exp_name: lstm_continuous
  action_type: continuous
  hidden_layer_size: 512
  max_updates: 500
  num_mini_batch: 8
  random_seed: 0
  save_model_freq: 10
worker:
  num_workers: 6
  worker_steps: 512
