ppo:
  entropy_coeff_schedule:
    init: 0.001
    final: 0.001
    pow: 1.0
    max_decay_steps: 0
  clip_range_schedule:
    init: 0.2
    final: 0.2
    pow: 1.0
    max_decay_steps: 0
  lr_schedule:
    init: 3.0e-5
    final: 3.0e-5
    pow: 1.0
    max_decay_steps: 0
  gamma: 0.99
  lamda: 0.95
  vf_loss_coeff: 0.5
recurrence:
  hidden_state_size: 256
  layer_type: gru
  reset_hidden_state: true
  sequence_length: 8
  use_lstm: true
train:
  K_epochs: 4
  device: cuda
  exp_name: lr_3e-5
  hidden_layer_size: 512
  max_updates: 20000
  num_mini_batch: 8
  random_seed: 0
  save_model_freq: 10
  use_rnd: false
  use_reward_scaling: true
  use_state_normailzation: false
worker:
  num_workers: 6
  worker_steps: 512
env:
  env_type: Unity
  env_name: CarSearch
  env_action_type: continuous
  env_win_path: ./UnityEnvs/CarSearch
  env_linux_path: ./UnityEnvs/CarSearch-linux/bin.x86_64
