K_epochs: 4
device: cuda
env_name: CartPole-v1
eps_clip: 0.2
exp_name: init
gamma: 0.99
has_continuous_action_space: false
lr_actor: 0.001
lr_critic: 0.0003
max_updates: 40
num_mini_batch: 4
ppo:
  entropy_coeff: 0.001
  vf_loss_coeff: 0.2
random_seed: 0
recurrence:
  hidden_state_size: 64
  layer_type: gru
  reset_hidden_state: true
  sequence_length: -1
  use_lstm: false
save_model_freq: 10
worker:
  num_workers: 16
  worker_steps: 256
