ppo:
  entropy_coeff: 0.001
  eps_clip: 0.2
  gamma: 0.99
  lamda: 0.95
  lr: 0.0001
  lr_std: 0.01
  vf_loss_coeff: 0.5
recurrence:
  hidden_state_size: 128
  layer_type: gru
  reset_hidden_state: true
  sequence_length: 8
  use_lstm: true
train:
  K_epochs: 4
  device: cuda
  env_name: LunarLander-v2
  exp_name: lstm_continue
  has_continuous_action_space: false
  hidden_layer_size: 64
  max_updates: 150
  num_mini_batch: 8
  random_seed: 0
  save_model_freq: 10
worker:
  num_workers: 8
  worker_steps: 512
