K_epochs: 80
device: cuda
env_name: LunarLander-v2
eps_clip: 0.2
exp_name: lstm
gamma: 0.99
has_continuous_action_space: true
i_episode: 1003
lr_actor: 0.0003
lr_critic: 0.001
max_updates: 120
num_mini_batch: 4
ppo:
  entropy_coeff: 0.001
  vf_loss_coeff: 0.1
random_seed: 0
recurrence:
  hidden_state_size: 32
  layer_type: gru
  reset_hidden_state: true
  sequence_length: 64
  use_lstm: true
resume: true
run_num: 2
save_model_freq: 10
update: 80
worker:
  num_workers: 6
  worker_steps: 1000
