ppo:
  entropy_coeff_schedule:
    init: 0.01
    final: 0.001
    pow: 1.0
    max_decay_steps: 250
  clip_range_schedule:
    init: 0.3
    final: 0.1
    pow: 1.0
    max_decay_steps: 250
  lr_schedule:
    init: 3.0e-3
    final: 3.0e-6
    pow: 1.0
    max_decay_steps: 300
  gamma: 0.99
  lamda: 0.95
  vf_loss_coeff: 0.3
recurrence:
  hidden_state_size: 64
  layer_type: gru
  reset_hidden_state: true
  sequence_length: 8
  use_lstm: true
train:
  K_epochs: 4
  device: cuda
  env_name: LunarLander-v2
  exp_name: continuous_gru
  action_type: continuous
  hidden_layer_size: 256
  max_updates: 300
  num_mini_batch: 8
  random_seed: 0
  save_model_freq: 10
worker:
  num_workers: 16
  worker_steps: 256
