ppo:
  entropy_coeff_schedule:
    init: 0.001
    final: 0.001
    pow: 1.0
    max_decay_steps: 0
  clip_range_schedule:
    init: 0.3
    final: 0.3
    pow: 1.0
    max_decay_steps: 0
  lr_schedule:
    init: 3.0e-3
    final: 3.0e-4
    pow: 1.0
    max_decay_steps: 150
  task_schedule:
    init: 0
    final: 0
    pow: 1.0
    max_decay_steps: 0
  gamma: 0.99
  lamda: 0.95
  vf_loss_coeff: 0.3
recurrence:
  hidden_state_size: 64
  layer_type: gru
  reset_hidden_state: true
  sequence_length: 8
  use_lstm: true
train:
  K_epochs: 4
  device: cuda
  exp_name: test
  action_type: discrete
  hidden_layer_size: 256
  max_updates: 200
  num_mini_batch: 8
  random_seed: 5230
  save_model_freq: 10
  multi_task: false
  use_state_normailzation: false
  use_reward_scaling: true
  use_rnd: false
  rnd_rate: 0.5
drq:
  use_drq: false
  drq_image_pad: 4
  drq_ray_pad: 4
  drq_M: 1
worker:
  num_workers: 6
  worker_steps: 256

env:
  env_type: gym
  env_name: MountainCar-v0
  env_action_type: discrete
