ppo:
  entropy_coeff_schedule:
    init: 0.001
    final: 0.001
    pow: 1.0
    max_decay_steps: 0
  clip_range_schedule:
    init: 0.3
    final: 0.3
    pow: 1.0
    max_decay_steps: 0
  lr_schedule:
    init: 3.0e-3
    final: 3.0e-4
    pow: 1.0
    max_decay_steps: 150
  gamma: 0.99
  lamda: 0.95
  vf_loss_coeff: 0.3
recurrence:
  hidden_state_size: 64
  layer_type: gru
  reset_hidden_state: true
  sequence_length: 8
  use_lstm: true
train:
  K_epochs: 4
  device: cuda
  env_name: MountainCar-v0
  exp_name: rnd_gru_decay
  action_type: discrete
  hidden_layer_size: 256
  max_updates: 200
  num_mini_batch: 8
  random_seed: 5230
  save_model_freq: 10
  use_reward_scaling: true
  use_state_normailzation: true
  use_rnd: true
  rnd_rate: 1.
worker:
  num_workers: 16
  worker_steps: 256
