ppo:
  entropy_coeff_schedule:
    init: 0.001
    final: 0.001
    pow: 1.0
    max_decay_steps: 0
  clip_range_schedule:
    init: 0.2
    final: 0.2
    pow: 1.0
    max_decay_steps: 0
  lr_schedule:
    init: 3.0e-5
    final: 3.0e-5
    pow: 1.0
    max_decay_steps: 0
  task_schedule:
    init: 1
    final: 0
    pow: 1.0
    max_decay_steps: 1000
  gamma: 0.99
  lamda: 0.95
  vf_loss_coeff: 0.5
recurrence:
  hidden_state_size: 512
  layer_type: lstm
  reset_hidden_state: true
  sequence_length: 16
  use_lstm: true
train:
  K_epochs: 4
  device: cuda
  exp_name: test
  hidden_layer_size: 512
  max_updates: 4000
  num_mini_batch: 8
  random_seed: 1234
  save_model_freq: 10
  multi_task: true
  use_state_normailzation: false
  use_reward_scaling: true
  use_rnd: true
  rnd_rate: 0.5
worker:
  num_workers: 6
  worker_steps: 512
env:
  env_name: UnityMultitask
  env_type: Unity_Multitask
  env_action_type: continuous
  env_win_path:
    [
      { "one_hot": [1, 0], "file_name": "UnityEnvs/UnityMultitask/Task0" },
      { "one_hot": [0, 1], "file_name": "UnityEnvs/UnityMultitask/Task1" },
    ]
  env_linux_path:
    [
      { "one_hot": [1, 0], "file_name": "UnityEnvs/UnityMultitask/Task0" },
      { "one_hot": [0, 1], "file_name": "UnityEnvs/UnityMultitask/Task1" },
    ]
