ppo:
  entropy_coeff_schedule:
    init: 0.001
    final: 0.001
    pow: 1.0
    max_decay_steps: 0
  clip_range_schedule:
    init: 0.2
    final: 0.2
    pow: 1.0
    max_decay_steps: 0
  lr_schedule:
    init: 3.0e-4
    final: 3.0e-4
    pow: 1.0
    max_decay_steps: 0
  gamma: 0.99
  lamda: 0.95
  vf_loss_coeff: 0.3
recurrence:
  hidden_state_size: 256
  layer_type: gru
  reset_hidden_state: true
  sequence_length: 16
  use_lstm: true
train:
  K_epochs: 4
  device: cuda
  env_name: Worm
  exp_name: gru
  action_type: continuous
  hidden_layer_size: 512
  max_updates: 2000
  num_mini_batch: 8
  random_seed: 0
  save_model_freq: 10
  use_rnd: true
  rnd_rate: 5
worker:
  num_workers: 2
  worker_steps: 256
